version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongo
    env_file: ./api/.env
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./api/db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - ./api/db/data:/data/db
      - ./api/db/seed:/seed

  api:
    image: node:12-alpine
    container_name: api
    env_file: ./api/.env
    depends_on:
      - mongo
    ports:
      - "5000:3000"
      - "587:587"
    volumes:
      - ./api:/data
    working_dir: /data
    command: ./node_modules/.bin/nodemon

  web:
    image: node:12-alpine
    container_name: web
    env_file: ./web/.env
    ports:
      - "80:3000"
    volumes:
      - ./web:/data
    working_dir: /data
    command: npm start
    stdin_open: true

  blockchain:
    # image: meboo/eosio-dev:2.1.0-CDT-1.8.0
    build: ./blockchain
    container_name: blockchain
    env_file: ./blockchain/.env
    ports:
      - "8888:8888"

    volumes:
      - ./blockchain/logs:/data
      - ./blockchain/data:/root/.local/share/eosio/nodeos/data
      - ./blockchain/wallet:/root/eosio-wallet
      - ./blockchain/keys:/keys
      - ./blockchain/contracts:/contracts
      - ./blockchain/lib:/eosio.cdt
